spring:
  data:
    redis:
      host: master.livef-cluster.wvgtmq.apn2.cache.amazonaws.com:6379
      port: 6379
      password: 1234
      ssl:
        enabled: true

  application:
    name: auth
  profiles:
    active: dev
  config:
    import: optional:configserver:http://admin:1234@livef.store:9000
jwt:
  secret: DYB7u9huTcS72Ti8HpLCxavcoO3Ca4LEvhhzrdxAmzoXwiChA4YVuFp58gs+TPvixqqat7jWuR/sRekiRn48xw==

oauth2:
  kakao:
    base-url: https://kauth.kakao.com/oauth/authorize
    client-id: a22f21c9bf9938f2cca8bb10c3810bad
    client-secret: PRmxqYdstGTbKtnaYFQtMjLylrToMx5X
    redirect-uri: https://livef.store/api/auth/kakao/callback